server:
  port: ${PORT:8080}

spring:
  data:
    mongodb:
      uri: ${DB_URI}

jwt:
  secret: ${JWT_SECRET:secret}

plaid:
  client-id: ${CLIENT_ID}
  public-key: ${PUBLIC_KEY}
  client-secret: ${CLIENT_SECRET}